apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: notification-binding
  namespace: default
spec:
  type: bindings.http
  version: v1
  metadata:
  - name: url
    value: "http://notification-service:8080/webhook"
  - name: method
    value: "POST"